version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:8.11.2-browsers

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: npm-install
          command: npm install
      - run:
          name: Run Unit Tests
          command: npm run test:ci
      - run:
          name: Build
          command: npm run ng build --prod --aot --progress=false
