version: 2
jobs:
  build-angular:
    build:
      docker:
        - image: circleci/node:latest-browsers

      working_directory: ~/repo

      steps:
        - checkout
        - run:
          name: Install Dependencies
          command: rm -rf node_modules && npm install
        - run:
          name: Run Unit Tests
          command: ng test --watch=false
        - run:
          name: Build
          command: ng build --prod
